"use strict";
function changeCount(type) {
    // const color = enemyPiece.isWhite ? "b" : "w";
    const countEl = document.querySelector(`.${type}Count`);
    const oldClassName = countEl.classList[2];
    countEl.classList.remove(oldClassName);
    const newClassName = oldClassName.replace(oldClassName.charAt(18), String(Number(oldClassName.charAt(18)) + 1));
    countEl.classList.add(newClassName);
}
changeCount("pawnb");
changeCount("pawnb");
changeCount("pawnb");
changeCount("pawnb");
changeCount("bishopb");
changeCount("bishopb");
changeCount("knightb");
changeCount("knightb");
changeCount("rookb");
changeCount("rookb");
changeCount("queenb");
changeCount("pawnw");
changeCount("pawnw");
changeCount("pawnw");
changeCount("pawnw");
changeCount("bishopw");
changeCount("bishopw");
changeCount("knightw");
changeCount("knightw");
changeCount("rookw");
changeCount("rookw");
changeCount("queenw");
